config/routes.rb
Rails.application.routes.draw do
  resources :countries do
    resources :cities
  end
  # You can have the root of your site routed with "root"
  root 'countries#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, :presence => true
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
    @country = Country.find(params[:country_id])
    @city = @country.cities.new
  end

  def create
    @country = Country.find(params[:country_id])
    @city = @country.cities.new(city_params)
    if @city.save
      flash[:notice] = "City: #{@city.name} successfully added!"
      redirect_to country_path(@city.country)
    else
      render :new
    end
  end

  def edit
    @country = Country.find(params[:country_id])
    @city = City.find(params[:id])
  end

  def update
    @country = Country.find(params[:country_id])
    @city = City.find(params[:id])
    if @city.update(city_params)
      redirect_to country_path(@city.country)
    else
      render :edit
    end
  end

  def destroy
    @country = Country.find(params[:country_id])
    @city = City.find(params[:id])
    @city.destroy
    redirect_to country_path(@city.country)
  end

  private
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      flash[:notice] = "Country: #{@country.name} successfully added!"
      redirect_to countries_path
    else
      render :new
    end
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update(country_params)
      redirect_to countries_path
    else
      render :edit
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to countries_path
  end

  private
  def country_params
    params.require(:country).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/_form.html.erb
<%= render 'layouts/errors', :object => @city %>

<%= form_for [@country, @city] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/cities/edit.html.erb
<h1>Edit city</h1>

<%= render 'form' %>

<% content_for(:footer) do %>
<br>
<%= link_to 'Back', country_path(@country) %>
<% end %>

app/views/cities/new.html.erb
<h2>New City</h2>

<%= render 'form' %>

app/views/countries/_form.html.erb
<%= render 'layouts/errors', :object => @country %>

<%= form_for @country do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.submit %>
<% end %>

app/views/countries/edit.html.erb
<h1>Edit country</h1>

<%= render 'form' %>

app/views/countries/index.html.erb
<% content_for(:title, "Countries | Wikipages") %>

<h1>Here are all the countries:</h1>

<ul>
  <% @countries.each do |country| %>
  <li><%= link_to country.name, country_path(country) %> |
  <%= link_to 'Edit', edit_country_path(country) %> |
  <%= link_to 'Delete', country_path(country),
  :data => {:confirm => "You sure?",
    :method => 'delete'} %>
  </li>
  <% end %>
</ul>

<button class="btn btn-primary"><%= link_to 'New Country', new_country_path %></button>

app/views/countries/new.html.erb
<h1>Add a new country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<% content_for(:title, "Country | Wikipages") %>

<h2>Welcome to <%= @country.name %>!</h2>

<% if @country.image_url %>
  <img src="<%= @country.image_url %>" alt="" width='700px' />
<% end %>
<h2>Here are your cities for <%= @country.name %>:</h2>
<% if @country.cities.any? %>

  <% @country.cities.each do |city| %>
    <h3><%= city.name %>
    <%= link_to 'Edit', edit_country_city_path(@country, city) %> |
    <%= link_to 'Delete', country_city_path(@country, city),
                                :data => {:confirm => "You sure?",
                                          :method => 'delete'} %>
    </h3>
  <% end %>
<% else %>
  <p>
    There are no cities yet!
  </p>
<% end %>

<%= link_to 'Create City', new_country_city_path(@country) %>

<% content_for(:footer) do %>
  <br>
  <%= link_to 'Back', countries_path %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <%= yield %>

  <%= yield(:footer) %>

</body>
</html>